channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - pandas == 1.1.3
  - azureml-core
  - azureml-defaults >= 1.0.45
- scikit-learn == 0.23.2
name: azureml_bc84c8b1e6f800381723c1af65ff7e9c
