channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - pandas == 1.1.3
  - azureml-core~=1.22.0
  - azureml-defaults >= 1.0.45
- scikit-learn == 0.23.2
name: azureml_d322234cf1103dbd7b07da4ab58adb31
